extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:import/react
rules:
    no-useless-escape: 1
    eqeqeq: 2
    react/no-find-dom-node: 0
    semi: 2
    react/prop-types:
      - 2
      - ignore:
          - children
    quotes:
      - 2
      - double
    import/named: 2
    import/export: 2
    import/no-mutable-exports: 2
    import/first: 2
    import/no-duplicates: 2
    import/no-unresolved:
      - 2
      -
        commonjs: true
        ignore:
          - "@randy\\.tarampi\\/\\w+"
    import/default: 2
    import/no-extraneous-dependencies: 1
    react/no-unescaped-entities: 0
parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
        jsx: true
        modules: true
        experimentalObjectRestSpread: true
env:
    node: true
    es6: true
    browser: true
plugins:
    - react
    - import
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .json
globals:
  __PHOTOS_URL__: false
  __CLIENT_URL__: false
